import "@styles/globals.css";
import Nav from "@components/Nav";
import Footer from "@components/Footer";
import { Inter } from "next/font/google";

import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

const styles = {
  pos: {
    alignSelf: "center"
  }
}


export const metadata = {
  title: "rp developer",
  description: "Generated by Roman Potachenski",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/x-icon" href="/assets/icons/favicon.ico" />
      </Head>
      <body>
        <Nav />
        <main style={styles.pos} className={inter.className}>{children}</main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
